version: "3.7"
services:
  app:
    build:
      args:
        user: automationTeam
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: automation
    container_name: automation-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - automation-net

  db:
    image: mysql:5.7
    container_name: automation-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - automation-net

  nginx:
    image: nginx:alpine
    container_name: automation-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - automation-net

networks:
  automation-net:
    driver: bridge